# Generated by Django 5.2.8 on 2025-11-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='contacto',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
